name: Build and Push Podman Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman buildah qemu-user-static

      - name: Authenticate with GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | podman login ghcr.io --username "${{ github.actor }}" --password-stdin

      - name: Enable Buildx for Multi-Platform Builds
        run: |
          podman buildx create --use
          podman buildx inspect --bootstrap
          
      - name: Build and Push Multi-Platform Docker Image
        run: |
          podman buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ github.actor }}/3d-print-calculators:latest \
            --push .
